name: Lint
on: [pull_request]

permissions:
  contents: read # for checkout

jobs:
  fmt:
    name: Code Format
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:1.9.5
    steps:
      - uses: actions/checkout@v4
      - run: terraform fmt --recursive -check=true

  validate:
    name: Validate
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:1.9.5
    steps:
      - uses: actions/checkout@v4
      - name: Validate Examples
        run: |
          for example in $(find examples -maxdepth 1 -mindepth 1 -type d); do
            cd $example
            terraform init -backend=false
            terraform validate
            cd -
          done

  tflint:
    name: TFLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: TFLint
        uses: docker://wata727/tflint
